/* Generated by Kconfiglib (https://github.com/ulfalizer/Kconfiglib) */
#define CONFIG_LOG_DEFAULT_LEVEL_DEBUG 1
#define CONFIG_LOG_DEFAULT_LEVEL 4
#define CONFIG_LOG_COLORS 1
#define CONFIG_ERROR_CHECK_SET_ERRNO 1
